### PR TITLE
Platform to 21

### PR DESCRIPTION
**Pull request by micronaut-build**
Update common files

### CODE REVIEW

**Comment by sdelamo** [comment]
We get 

buildSrc:compileKotlin'.
> Unknown Kotlin JVM target: 21

@timyates what should we do?

**Comment by timyates** [comment]
Kotlin doesn't support Java 21 yet... so we have to downgrade the JVM target

**Review by melix — APPROVED** [review]

**Comment by sdelamo** [comment]
is this because it is a `buildSrc/build.gradle.kts`?

**Comment by sdelamo** [comment]
@wetted you may need to apply a similar [fix](https://github.com/micronaut-projects/micronaut-platform/pull/973/commits/1322951b7fe90fdb85f794d38712e020eb16ec9a) in other modules.

**Pull request merged**
