### PR TITLE
Update oracle-cloud to 3.0.5

### PR DESCRIPTION
**Pull request by timyates**
Should fix the [object-storage oracle guide for maven](https://github.com/micronaut-projects/micronaut-guides/pull/1333#issuecomment-1735906982)

### CODE REVIEW

**Comment by timyates** [comment]
@n0tl3ss @alvarosanchez So this is failing as

```
* What went wrong:	
Execution failed for task ':micronaut-platform:checkVersionCatalogCompatibility'.	
> Version catalogs are not compatible:	
  The following libraries were present in the baseline version but missing from this catalog:	
    - micronaut-oraclecloud-bmc-computecloudatcustomer	
    - micronaut-oraclecloud-bmc-fleetsoftwareupdate	
    - micronaut-oraclecloud-bmc-osmanagementhub	
    - micronaut-oraclecloud-bmc-ocicontrolcenter
```

I'm guessing this is because we used to just grab the latest, whereas [now we are looking at `3.15.0`](https://github.com/micronaut-projects/micronaut-oracle-cloud/blob/3.0.x/gradle/libs.versions.toml#L17)

Are these ok to ignore in a patch release?

**Comment by timyates** [comment]
I think we only added them in a point release as well (3.0.4) so we may be ok?

https://repo1.maven.org/maven2/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-computecloudatcustomer/

**Comment by n0tl3ss** [comment]
I think we are good, check: https://github.com/micronaut-projects/micronaut-oracle-cloud/commit/5484460266b00733bd5e7e18c3305b7a51dab411

**Comment by timyates** [comment]
👍 Pushed a suppression

**Review by n0tl3ss — APPROVED** [review]

**Review by sdelamo — APPROVED** [review]

**Pull request merged**
